version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule: 
      interval: "daily"
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
