# --- required

## Ingress class
ingressClass: traefik

## Ingress host
host: example.com

## Key used for encryption. Can be any non-empty value.
credentialsCoderKey: ur2QsZu8WUamepbo1EOlqXaS5ZiNvdCueEy32eJS

## Type of the oneko service.
## Possible values: ClusterIP, LoadBalancer
serviceType: ClusterIP

# --- optional

## Kubernetes token of the service account secret. Use the following command to fetch the token:
## kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep o-neko | awk '{print $1}')
## See also: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L401
# kubernetesAuthToken: <TOKEN>

## Kubernetes Url. This property is typically read from the Kubernetes configuration file. Leave it blank if you want to access the
## Kubernetes Cluster oneko is deployed to.
# kubernetesUrl: <URL>

## Kubernetes Port. This property is typically read from the Kubernetes configuration file. Leave it blank if you want to access the
## Kubernetes Cluster oneko is deployed to.
# kubernetesPort: <PORT>